apiVersion: v1
kind: Service
metadata:
  name: pipeline-controls-demo
  labels:
    app: pipeline-controls-demo
spec:
  type: ClusterIP
  selector:
    app: pipeline-controls-demo
  ports:
    - port: 80
      targetPort: 8080
